### ISSUE TITLE
 ld: library not found for -lRNCookieManagerIOS error

### ISSUE THREAD

**Issue by DIGITALSQUAD** [react-native-community/react-native-cookies#7]
### Question
I have swiched from [joeferraro/react-native-cookies](https://github.com/joeferraro/react-native-cookies), but does not work.

### Error 1: `react-native run-ios` fails with errors below
```
Linking MyAppName
⚠️  ld: directory not found for option '-L/Users/mac_user/Projects/my_app/ReactNative/MyAppName/ios/build/MyAppName/Build/Products/Debug-iphonesimulator/React'

❌  ld: library not found for -lRNCookieManagerIOS

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. 
To debug build logs further, consider building your app with Xcode.app, by opening MyApp
```
I did these solutions, but not solved by these solutions.
- [Created new XCode Configuration and Scheme - linker is suddenly failing](https://stackoverflow.com/questions/39626055/created-new-xcode-configuration-and-scheme-linker-is-suddenly-failing) 
- [Can't link library in Xcode with new build configuration](https://github.com/oblador/react-native-vector-icons/issues/223)

### Error 2: Run with Xcode build successfully but it raise error with code
`CookieManager.get(myurl)`
![スクリーンショット 2020-01-15 18 17 56](https://user-images.githubusercontent.com/6149827/72421205-66bc7a80-37c3-11ea-9ac5-1b9ce5f882cc.png)

I did `Xcode > Product > Clean` but does not solved.

**Comment by safaiyeh** [comment]
Thanks for the issue @DIGITALSQUAD, I'll check this out sometime today.

**Comment by DIGITALSQUAD** [comment]
Thanks for your reply @safaiyeh. 
I don't know why but the **ld: library not found for -lRNCookieManagerIOS error** has fixed while rebasing commits, redo yarn install and rerun `react-native run-ios`. 
However the argument error is not fixed yet.

**Comment by safaiyeh** [comment]
Hi @DIGITALSQUAD 

I could not reproduce the error

```javascript
const myurl = 'https://google.com';
CookieManager.get(myurl);
```

Could you make sure to unlink and remove all setup from `joeferraro/react-native-cookies`. Then set up this module from scratch. Might be conflicting files.

**Comment by DIGITALSQUAD** [comment]
Thanks for your advice @safaiyeh 
I noticed that **RNCookieManagerIOS.xcodeproj** and **libRNCookieManagerIOS.a** is grayed out.
So manually linked those and now works fine.
Thanks a lot!
